languageCode = "ja"
title = "Today I learned"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/kimihito\">kimihito</a> 2018"
baseurl = "https://kimihito.github.io/til"
enableGitInfo = true


[params]
repourl = "https://github.com/kimihito/til/"
latest = "最終更新日"

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "ruby"]

[[params.social]]
url = "https://github.com/kimihito"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/kimihito_"
fa_icon = "fa-twitter"

[[params.social]]
url = "/til/index.xml"
fa_icon = "fa-rss"